services:
  asp_rest_api:
    image: asp_rest_api_image
    build:
      context: .
      dockerfile: ./ASP_Rest_API/Dockerfile
    ports:
     - "8080:8080"
     #- "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 # Stellt sicher, dass nur HTTP verwendet wird
    depends_on:
      - tododal

  webui:
    image: web_ui_image
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
     - "80:80"
    volumes:
      - ./WebUI/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./WebUI/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - asp_rest_api
   
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Binde das Volume für persistente Datenspeicherung ein

  tododal:
    image: tododal_image
    build:
      context: .
      dockerfile: ./TodoDAL/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - db
 
volumes:
    postgres_data:  # Definiertes Volume für persistente Datenspeicherung von PostgreSQL