version: '3.8'

services:
  asp_api_demo:
    image: asp_api_demo_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
